### ISSUE TITLE
A smaller release, with something for everyone.

### ISSUE THREAD

**Issue by asanetargoss** [asanetargoss/HardcoreAlchemy#4]
I'm going to be honest, after working on the instinct system for so long, I'm pretty tired. So, this is going to be a smaller release! This time, I'm going to try to be a bit more realistic about what I can accomplish.

**Part 1: New features**

- [x] A small improvement to Nether exploration
- [x] A small improvement to morphing
- [x] Update Changeling on top of the upcoming Metamorph 1.2 release
- [x] Fix bugs introduced by Changeling update

I may add features to the above list as I have motivation. Once I either accomplish everything, or don't have the motivation to add more to the list, I will move on to Part 2.

**Part 2: Bugfixes**

- [x] Fix the bug with crafting items with dietary restrictions
- [x] Fix player death sounds
- [x] Fix inventory items getting swapped just after opening the inventory
- Fix crashes as they come up

**Comment by asanetargoss** [comment]
0.5.0 has been released.
